import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display, Lora} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: "700",
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} ${playfair.variable}`}
          style={{backgroundColor: '#CBC3E3'}}
      >
        {children}
      </body>
    </html>
  );
}
